In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
X = torch.from_numpy(inputs)
Y = torch.from_numpy(targets)


$$
\hspace{2.5cm} X \hspace{1.1cm} \times \hspace{1.2cm} W^T \hspace{1.2cm}  + \hspace{1cm} b \hspace{2cm}
$$

$$
\left[ \begin{array}{cc}
73 & 67 & 43 \\
91 & 88 & 64 \\
\vdots & \vdots & \vdots \\
69 & 96 & 70
\end{array} \right]
%
\times
%
\left[ \begin{array}{cc}
w_{11}& w_{21} \\ 
w_{12} & w_{22} \\
w_{13} & w_{23}\\
\end{array} \right]
%
+
%
\left[ \begin{array}{cc}
b_{1} & b_{2}\\
\end{array} \right]
$$

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
dataset = torch.utils.data.TensorDataset(X,Y)

In [7]:
# Define data loader
trainloader = torch.utils.data.DataLoader(dataset,batch_size=10)

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [9]:
# Define model
model = nn.Linear(X.shape[1],Y.shape[1])
print(model.state_dict())
model.parameters()

OrderedDict([('weight', tensor([[ 0.4827,  0.1309,  0.3063],
        [ 0.3904,  0.1613, -0.3601]])), ('bias', tensor([-0.4368,  0.5353]))])


<generator object Module.parameters at 0x7f9db7b1d1d0>

### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [10]:
# Define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=1e-4)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [11]:
# Import nn.functional
import torch.nn.functional as F

In [12]:
# Define loss function
loss_fn = F.mse_loss

### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [13]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in trainloader:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(yb,pred)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
        print('Training loss: ', loss_fn(model(X), Y))

In [14]:
# Train the model for 100 epochs
fit(100 , model , loss_fn, optimizer)

Training loss:  tensor(1590.9724, grad_fn=<MseLossBackward>)
Training loss:  tensor(878.0040, grad_fn=<MseLossBackward>)
Training loss:  tensor(546.3942, grad_fn=<MseLossBackward>)
Training loss:  tensor(375.9174, grad_fn=<MseLossBackward>)
Training loss:  tensor(277.6564, grad_fn=<MseLossBackward>)
Training loss:  tensor(214.7118, grad_fn=<MseLossBackward>)
Training loss:  tensor(171.0257, grad_fn=<MseLossBackward>)
Training loss:  tensor(139.0691, grad_fn=<MseLossBackward>)
Training loss:  tensor(114.9370, grad_fn=<MseLossBackward>)
Training loss:  tensor(96.3634, grad_fn=<MseLossBackward>)
Training loss:  tensor(81.8932, grad_fn=<MseLossBackward>)
Training loss:  tensor(70.5195, grad_fn=<MseLossBackward>)
Training loss:  tensor(61.5110, grad_fn=<MseLossBackward>)
Training loss:  tensor(54.3219, grad_fn=<MseLossBackward>)
Training loss:  tensor(48.5385, grad_fn=<MseLossBackward>)
Training loss:  tensor(43.8448, grad_fn=<MseLossBackward>)
Training loss:  tensor(39.9980, grad_fn=<MseLo

In [15]:
# Generate predictions
preds = model(X)
preds

tensor([[ 57.1264,  70.5329],
        [ 81.9571,  99.4890],
        [119.3221, 135.2866],
        [ 21.2638,  37.6603],
        [101.2922, 116.8125],
        [ 57.1264,  70.5329],
        [ 81.9571,  99.4890],
        [119.3221, 135.2866],
        [ 21.2638,  37.6603],
        [101.2922, 116.8125],
        [ 57.1264,  70.5329],
        [ 81.9571,  99.4890],
        [119.3221, 135.2866],
        [ 21.2638,  37.6603],
        [101.2922, 116.8125]], grad_fn=<AddmmBackward>)

In [16]:
# Compare with targets
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

Now we can define the model, optimizer and loss function exactly as before.

#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)


 

In [17]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()

In [19]:
from sklearn.model_selection import train_test_split

X_Train,X_Test,Y_Train,Y_Test = train_test_split(inputs,targets,test_size=0.2,random_state=147)

In [20]:
model1.fit(X_Train,Y_Train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
Y_pred = model1.predict(X_Test)

In [22]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_Test,Y_pred))
Y_pred,Y_Test

1.3399835


(array([[20.115925, 37.132072],
        [20.115925, 37.132072],
        [56.94927 , 69.93347 ]], dtype=float32), array([[22., 37.],
        [22., 37.],
        [56., 70.]], dtype=float32))